version: 1

disable_existing_loggers: false

formatters:
  simple:
    format: '%(asctime)-1s [%(name)s] %(levelname)s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: DEBUG
    formatter: simple

loggers:
  aiohttp:
    level: WARN
    propagate: false

root:
  level: DEBUG
  handlers:
    - console
